#!/usr/bin/bash

set -e

prefix=$(cat prefix)
appdatadir="${prefix}/share/appdata"
mkdir -p "${appdatadir}"
cp -a org.snap4arduino.App.appdata.xml "${appdatadir}"

appsdir="${prefix}/share/applications"
mkdir -p "${appsdir}"
cp -a org.snap4arduino.App.desktop "${appsdir}"
